# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-18 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proceso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='solvencia',
            field=models.BooleanField(default=True),
        ),
    ]
