# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proceso', '0002_auto_20170617_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='programas',
            name='solicitudes',
            field=models.ManyToManyField(related_name='programas', to='Proceso.Solicitud'),
        ),
    ]
