# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proceso', '0004_solicitud_correo_listo'),
    ]

    operations = [
        migrations.AddField(
            model_name='programas',
            name='nombre',
            field=models.CharField(default='x', max_length=50),
            preserve_default=False,
        ),
    ]
