# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proceso', '0006_auto_20170621_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='estatus',
            field=models.CharField(choices=[('R', 'Recibido'), ('P', 'Procesado'), ('V', 'Verificacion'), ('EF', 'A la espera de firma'), ('E', 'Entrega'), ('F', 'Finalizado')], default='R', max_length=10),
        ),
    ]
