# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proceso', '0007_auto_20170622_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programas',
            name='solicitudes',
            field=models.ManyToManyField(blank=True, related_name='programas', to='Proceso.Solicitud'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estatus',
            field=models.CharField(choices=[('R', 'Recibida'), ('P', 'Procesada'), ('V', 'Verificacion'), ('EF', 'Espera de firma'), ('E', 'Entregada'), ('F', 'Finalizada')], default='R', max_length=10),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_creacion',
            field=models.DateTimeField(),
        ),
    ]
