# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proceso', '0010_auto_20170624_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='estatus',
            field=models.CharField(choices=[('Recibida', 'Recibida'), ('Procesada', 'Procesada'), ('Verificacion', 'Verificacion'), ('Espera de firma', 'Espera de firma'), ('Firmada', 'Firmada'), ('Entregada', 'Entregada'), ('Finalizada', 'Finalizada')], default='Recibida', max_length=20),
        ),
    ]
