# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proceso', '0011_auto_20170624_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='estatus',
            field=models.CharField(choices=[('R', 'Recibida'), ('P', 'Procesada'), ('V', 'Verificacion'), ('EF', 'Espera de firma'), ('FI', 'Firmada'), ('E', 'Entregada'), ('F', 'Finalizada')], default='R', max_length=20),
        ),
    ]
